import type { Metadata } from "next";
import { Geist, Geist_Mono, Open_Sans, Dancing_Script, Satisfy } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar/navbar";
import Footer from "../components/Footer/footer";


const satisfy = Satisfy({
  variable: "--font-satisfy",
  subsets: ["latin"],
  weight: ["400"],
});


const dancingScript = Dancing_Script({
  variable:"--font-dancing-script",
  subsets: ["latin"],
  weight: ["700", "700", "700", "700", "700"],

});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const openSans = Open_Sans({
  variable: "--font-open-sans", // A variável CSS que vamos usar
  subsets: ["latin"], 
  weight: ["700", "700", "700", "700", "700"], 
  style: ["normal", "italic"],
});

export const metadata: Metadata = {
  title: "Ínicio - O Mestre Barbeiro",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${openSans.variable} ${dancingScript.variable} ${satisfy.variable} h-full antialiased`}
    >
      <body className="min-h-full min-w-full flex flex-col">
        {children}
        <Footer />
        </body>
    </html>
  );
}
